version: '3.7'
services:
  backend:
    build: 
      context: backend-python/
      dockerfile: Dockerfile
    init: true
    networks:
    - application
  frontend:
    build: 
      context: frontend-node/
      dockerfile: Dockerfile
    init: true
    networks:
    - application
    ports:
    - "9091-9095:8080"
    depends_on:
    - backend
networks:
  application:
    name: application